- name: run a command on remote hosts
  hosts: localhost
  become: yes 
  tasks:
    - name: checking path
      ansible.builtin.command:
        cmd: ls -l    # Specify the command directly using 'cmd'
      register: USER

    - name: storing and checking
      ansible.builtin.debug:
        msg: "{{ USER }}"    # Use 'USER' variable to access the output
