- name: run a command on remote hosts
  hosts: localhost
  become: yes 
  tasks:
    - name: checking path
      ansible.builtin.command:
        cmd: ls -l 
        register: USER

    - name: storing and checking
      ansible.builtin.debug:
        msg: "{{ USER }}"