- name: run a command on remote hosts
  hosts: localhost
  become: yes 
  tasks:
    - name: checking path
      ansible.builtin.command:
        argv: ls -l /var/logs

    - name: storing and checking
      ansible.builtin.debug:
        msg: "{{ argv }}"