- name: Configuring Frontend
  hosts: Frontend
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx 
        state: latest

    - name: start and enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Delete contents of a directory
      ansible.builtin.file:
        path: /usr/share/nginx/html/*
        state: absent
        recurse: yes


    
