- name: Configuring Frontend
  hosts: Frontend
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx 
        state: latest

    - name: start and enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Clear contents of a file
      ansible.builtin.copy:
        dest: /usr/share/nginx/html/*
        content: ""
        force: yes


    
