- name: Setting up MySQL Root Password
  hosts: db
  become: yes
  tasks:
    - name: printing hello
      ansible.builtin.shell:
        cmd: echo "Hello World"
      register: MSG

    - name: storing
      ansible.builtin.debug:
        msg: "{{ MSG }}"
