- name: Playbook with vars_prompt
  hosts: localhost
  vars_prompt:
    - name: name
      prompt: "Enter your name"
      private: no  # Indicates whether the input should be hidden (e.g., for passwords)
    - name: age
      prompt: "Enter your age"
      private: no

  tasks:
    - name: Display user input
      ansible.builtin.debug:
        msg: "Hello, {{ Name }}! You are {{ Age }} years old."
