- name: Creating a directory
  ansible.builtin.file:
    path: "{{ Directory_path }}"
    state: directory

- name: Downloading application code
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ file_name }}-v2.zip
    dest: "{{ file_path }}"

- name: unzip backend file 
  ansible.builtin.unarchive: #When remote_src is set to yes, it indicates that the source archive file exists on the remote host. 
    src: "{{ file_path }}"
    dest: "{{ Directory_path }}"
    remote_src: yes 