- name: "Configure server based on component"
  hosts: all
  connection: local
  become: yes
  tasks:
    - name: "Include role based on component variable"
      include_role:
        name: "{{ component }}"
  vars_files:
    - "variables-dev.yml"
