- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx 
    state: latest

- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Delete contents of a directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: run common tasks
  ansible.builtin.import_role:
    name: common

- name: setting up cofigurtion
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
    - Restart nginx

# - name: Restart nginx
#   ansible.builtin.templates:
#     name: nginx
#     state: restarted
  